line_length: 150
file_length: 500

disabled_rules:
  - todo
  - variable_name
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - type_name

opt_in_rules:
 - closure_spacing
 - conditional_returns_on_newline
 - empty_count
 - explicit_init
 - overridden_super_call
 - redundant_nil_coalescing
 - nimble_operator
 - attributes
 - closure_end_indentation
 - first_where
 - number_separator
 - operator_usage_whitespace
 - prohibited_super_call